---
title: '20181226'
author: "ichia"
date: "2018年12月26日"
output: html_document
---

```{r}
plasticContainer <- list(
  greenBox=c("paper","scissor"),     # location 1
  redBox=c(1L,3L,2.5),               # location 2
  blueBox=c(TRUE,FALSE,TRUE,TRUE)    # location 3
)
```

```{r}
plasticContainer[c("greenBox","redBox")] 
# or plasticContainer[c(1,2)]
```

```{r}
plasticContainer[c("greenBox")] 
# or plasticContainer[c(1,2)]
```

```{r}
plasticContainer$greenBox[[1]]
#Atomic vector c()
#R裡的Vectors有兩大類：Atomic vectors(就是c())、Lists
```
```{r}
install.packages("plotly")
```
```{r}

download.file("https://github.com/tpemartin/github-data/blob/master/plotly_4070_neda.Rda?raw=true",destfile = "plotly_4070_neda.Rda")
load("C://Users//ichia/Desktop//Github//inclass410579027//practice4105//plotly_4070_neda.Rda")
library(plotly)
plotly_4070_neda #下載有問題
list.files()
load(file = "plotly_4070_neda.Rda")
readRDA(file = "plotly_4070_neda")
install.packages("psych")
library(psych)
tp <- read.file("plotly_4070_neda")
temp$borrowCount
```

