---
title: '20181031'
author: "ichia"
date: "2018年10月31日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(googlesheets)
gs_auth(new_user = TRUE)
gsSurvey<-gs_key("1mC9bnxj11NCNoOCw0Vmn4nxERbHtLjeGo9v9C9b2GDE")  #download sheet information as an object
classSurvey<-gs_read(gsSurvey,ws=1) #access the 1st worksheet
```


```{r}
library(stringr)
aa<-(str_sub(classSurvey$`居住地行政區`,1,3))
classSurvey[aa == "台北市",3] #3也可以用C("姓名")表達
```
```{r}
cc <- classSurvey[aa == "台北市",3]
cc$`姓名`
```
 #5.4.7 generic replacement
```{r}
names(gsSurvey)
gsSurvey$links$type[2]
```
```{r}
names(StuDF)[2] <- c("姓名")
names(StuDF)
```
```{r}
library(readr)
student <- read_csv("https://raw.githubusercontent.com/tpemartin/course-107-1-programming-for-data-science/master/data/student.csv")
library(dplyr)
library(magrittr)
student %<>% mutate(
  身高級距=cut(身高,c(0,150,155,160,165,170,175,180,185,200)))
```
```{r}
levels(student$`身高級距`)<- c("小個子","小個子","小個子","小個子","小個子","中等個子","中等個子","高個子","高個子")
head(student$`身高級距`)
levels(student$`身高級距`)<-

levels(student$`身高級距`)[1:5] <- c("小個子")
(student$`身高級距`)[6:7] <- c("中等個子")
(student$`身高級距`)[8:9] <- c("高個子")
head(student)
```
```{r}
student$`新身高級距` <- student$`身高級距`
head(student$新身高級距)
levels(student$`新身高級距`)[1:3] <- c("(0,160]")
levels(student$新身高級距)
```
 
