---
title: '20181024'
author: "ichia"
date: "2018年10月24日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#讀取雲端資料
```{r}
library(googlesheets)
gs_auth(new_user = TRUE)
gsSurvey<-gs_key("1mC9bnxj11NCNoOCw0Vmn4nxERbHtLjeGo9v9C9b2GDE")  #download sheet information as an object
classSurvey<-gs_read(gsSurvey,ws=1) #access the 1st worksheet
class(classSurvey)
names(classSurvey) 

```

```{r}
StuDF <- data.frame(
  StuID=c(1,2,3,4,5),
  name=c("小明","大雄","胖虎","小新","大白"),
  score=c(80,60,90,70,50) #變數一,二,三
  )
StuDF 
as.character(StuDF$name) <- StuDF$name #把它的類別轉回來

#以下法二 不要字串進來就被當factor
StuDF <- data.frame(
  StuID=c(1,2,3,4,5),  #變數一
  name=c("小明","大雄","胖虎","小新","大白"),
  score=c(80,60,90,70,50)
  #痾沒跟到
  )


names(StuDF) #告訴你資料框有哪些
colnames(StuDF)
```

#抽取特定數據
```{r}
StuDF
StuDF[1,2] #1,2指row index,column index
StuDF[c(T,F,F,F,F),c(F,T,F)] #跟上面那行比,另一種表示法
a<-c(T,T,F,F,T,F,F)
sum(a)
StuDF[c(T,F,F,T,F),]

StuDF[,2]
StuDF[1,]
StuDF[c(1,4),]
StuDF[c(1,4),c(2,3)]
StuDF[c(1,4),]
StuDF[-c(1,4),] #負號表示不要那個
StuDF[c(1:3),]
StuDF[c(1:3,5),] 
```
```{r}
x<-matrix(1:12,ncol=3)
y <- matrix(1:10,nrow=2,ncol=5)
y
apply(y,2,sum)
x <- cbind(x1 = 3, x2 = c(4:1, 2:5))
?cbind
x
for (n in 1:10){ sum(n)
}
n
df <- tibble(
  a= rnorm(10),b=rnorm(10),c=rnorm(10),d=rnorm(10))
head(df)
median(df$a)
median(df$b)
output <- vector("double",ncol(df))
 for(i in seq_along(df)){output[[i]] <- median(df[[i]]) }
```

#作業二第一題ipeen
```{r}
strsplit(iPeenData$`均消`," ")[2]
str_extract(iPeenData$`均消`,"[0-9]+") #正規表達法
str_split_fixed(iPeenData$`均消`," ",n=Inf)[,2]
```

#助教練習四
```{r}
library(readr)
TyphoonData <- read_csv("https://raw.githubusercontent.com/GaryLKL/course-programming-for-ds-Quiz/master/TyphoonData.csv")
TyphoonData$`近臺強度` <- as.factor(TyphoonData$`近臺強度`)
class(TyphoonData$`近臺強度`)

head(TyphoonData$`最低氣壓(hPa)`)
TyphoonData$`最低氣壓(hPa)`<-as.numeric(TyphoonData$`最低氣壓(hPa)`)

TyphoonData$
#for (單一變數 in 參數向量){ 程式碼 }
a <- which(colnames(dataset) %in% c("TyphoonData$`7級風暴風半徑(km)`","TyphoonData$`10級風暴風半徑(km)`","TyphoonData$`最低氣壓(hPa)`","TyphoonData$`最大風速(m/s)`") 
  


i <- TyphoonData
for(i in c(1,2,7,9)){as.numeric[i]} {[[i]] <- as.numeric(TyphoonData[[i]])}


as.numeric(TyphoonData$`最大風速(m/s)`)
as.numeric(TyphoonData$`7級風暴風半徑(km)`)
as.numeric(TyphoonData$`10級風暴風半徑(km)`)
class(TyphoonData$`7級風暴風半徑(km)`)
class(TyphoonData$`最低氣壓(hPa)`)
```

```{r}
library(readr)
TyphoonData <- read_csv("https://raw.githubusercontent.com/GaryLKL/course-programming-for-ds-Quiz/master/TyphoonData.csv")
index1 <- which(TyphoonData$`年份` >= 2009) 
index1 <- (TyphoonData$`年份` >= 2009)
head(TyphoonData[index1,])
table(TyphoonData[index1,]$`近臺強度`)


index2 <- TyphoonData$`年份` %in% 2009:2018
head(index2)
index2
TyphoonData[index2,]$`近臺強度`

a <- which(TyphoonData[index2,]$`近臺強度` == "中度")
max(a)
```

